[toolchain]
# We can not use the latest version of Rust because of the following assertion:
# https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html#asserting-unsafe-preconditions
channel = "1.77.2"